### ISSUE TITLE
[CRITICAL] Problem with changing timeZone

### ISSUE THREAD

**Issue by markowanga** [nowakprojects/KtTimeTraveler#16]
Hello,

In time provider You have hardcoded zoneID -- it can changed when it's moving to summer and winter time.

**Comment by MateuszNaKodach** [comment]
According to those articles:
- https://www.baeldung.com/java-daylight-savings
- https://stackoverflow.com/questions/52113545/how-does-java-manage-summertime
- https://stackoverflow.com/questions/52614074/how-to-manually-set-the-daylight-saving-dst-shift-date-in-java

Looks like there is no bug in the library. Time zone can by configured in application properties (for spring boot starter) or passed to TimeProvider.

**Comment by markowanga** [comment]
Bug was in other place in app
